### PR TITLE
Update package-lock.json

### PR DESCRIPTION
**Pull request by djwester**

### CODE REVIEW

**Comment by djwester** [comment]
@svanherk I've limited it to just the repos I want to update translations for but still see issues - And ideas?

**Comment by djwester** [comment]
actually it might working after all - things just initially looked red, but on page refresh it looks like the build is running

**Comment by svanherk** [comment]
Yeah this seems good to me, no core UI components updated so shouldn't be any WCAG work leaking in here

**Comment by svanherk** [comment]
(Unless rubrics has hardcoded in their darker border changes)

**Pull request merged**
