### PR TITLE
tightening up CSS autoprefixer

### PR DESCRIPTION
**Pull request by dlockhart**
This had fallen slightly out of date compared to our supported browsers. Based on punching these into [browser.ist](http://browserl.ist), here's the before & after:

Before (`Last 3 versions, Firefox ESR, IE >= 11, Safari >= 9`)
- Edge: 17, 16, 15
- Firefox: 61, 60, 59, 52 
- IE: 11, 10, 9
- Chrome: 67, 66, 65
- Opera: 53, 52, 51
- Safari: 11.1, 11, 10.1, 10, 9.1, 9
- iOS Safari: 11.3-11.4, 11.0-11.2, 10.3

After (`last 2 versions, Firefox ESR, IE >= 11, ios_saf >= 10, not dead`)
- Edge: 17, 16
- Firefox: 61, 60, 52
- IE: 11
- Chrome: 67, 66
- Opera: 53, 52
- Safari: 11.1, 11
- iOS Safari: 11.3-11.4, 11.0-11.2, 10.3, 10.0-10.2

Diff:
- Dropped Edge 15
- Dropped Firefox 59
- Dropped IE 10 & 9
- Dropped Chrome 65
- Dropped Opera 51
- Dropped Safari 10.1, 10, 9.1, 9
- Added iOS Safari 10.0-10.2

I'll still wait until after branching Friday to merge this, just in case I'm missing something.

### CODE REVIEW

**Comment by dlockhart** [comment]
Hmm, the older version of postcss/autoprefixer is hating the "not dead" (ha). Will fix.

**Comment by dlockhart** [comment]
This change also reduces the size of `bsi.min.css` from 122 KB to 113 KB.

**Comment by dbatiste** [comment]
Nice!

**Comment by dbatiste** [comment]
On a side note, I wonder how much obsolete browser prefix CSS could be removed from monolith CSS.

**Comment by dlockhart** [comment]
Haha, probably a fair bit. I'll add it to the dragon slayer list...

**Pull request merged**
