### PR TITLE
Update d2l-my-courses

### PR DESCRIPTION
**Pull request by ryantmer**
Includes a fix for an animation bug in IE11, and some minor spacing tweaks (removes extra right-side space).

### CODE REVIEW

**Comment by dlockhart** [comment]
@ryantmer did this PR get lost?

**Comment by ryantmer** [comment]
@dlockhart Whoops, sure did. I'll update and merge it, my bad! (Although I think we have a new release as well, so might just close + new PR)

**Comment by ryantmer** [comment]
Nope, haven't released since then. Rebased, I'll merge once CI passes. Thanks for noticing this, totally slipped my mind!

**Comment by dlockhart** [comment]
np!

**Pull request merged**
