### PR TITLE
Fix scrolling inside <dialog-iframe> for mobile version of Safari

### PR DESCRIPTION
**Pull request by YMoskovko**
[see](https://trello.com/c/ozOZHi45/122-bug-ios-prod-can-t-scroll-versioning-list) for the additional description

### CODE REVIEW

**Comment by dlockhart** [comment]
Hi Yurii -- why is momentum scrolling needed? I see quite a few references to this CSS property online causing issues with z-index. Sorry I can't access the Trello issue you referenced as I don't have permission.

**Comment by YMoskovko** [comment]
I added that to fix the scrolling on a mobile Safari (iPad, iPhone). I’m not good in css and Web development, but this fix allowed us to scroll content inside iframe element.

**Comment by omsmith** [comment]
Seems in line with what was [done in activity-viewer](https://github.com/Brightspace/activity-viewer/blob/master/src/viewers/link/link.scss)

**Comment by dlockhart** [comment]
Well at least it's consistent. Alright, I'm OK with this... @YMoskovko is your team going to handle the testing once this gets in?

**Comment by YMoskovko** [comment]
I asked @wolfpet about that

**Comment by dlockhart** [comment]
@YMoskovko Alright I'm going to merge this and assuming that someone will test it :)

This won't show up in 10.6.11 right away, but will as soon as someone does a release of BSI and upgrades the LMS to use it -- likely in the next couple of days.

**Comment by YMoskovko** [comment]
Thank you, Dave. I'll ask our QA to verify.

**Pull request merged**
