### PR TITLE
US127858 [AQ] New Temporary Assessment Quality Dashboard Page. Publish the dashboard to CDN

### PR DESCRIPTION
**Pull request by Vitalii-Misechko**
[US127858](https://rally1.rallydev.com/#/23525809118d/portfolioitemstreegrid?detail=%2Fuserstory%2F603047932448&fdp=true?fdp=true): [AQ] New Temporary Assessment Quality Dashboard Page

PR publishes the dashboard to CDN. It also registers repo for serge translations

FYI @anhill-D2L @hyehayes @johngwilkinson @NicholasHallman @bemailloux

### CODE REVIEW

**Review by bemailloux — APPROVED** [review]

**Comment by Vitalii-Misechko** [comment]
Fix localization validation https://github.com/Brightspace/insights-assessment-quality-dashboard/pull/7

**Review by johngwilkinson — APPROVED** [review]
We should add OSLO support as well.

**Comment by Vitalii-Misechko** [comment]
@johngwilkinson 

> We should add OSLO support as well.

I agree. Should I add it now or we can postpone it till 

[US124002](https://rally1.rallydev.com/#/23525809118d/portfolioitemstreegrid?detail=%2Fuserstory%2F483493531896&fdp=true?fdp=true): [AQ] Translations

**Comment by johngwilkinson** [comment]
> @johngwilkinson
> 
> > We should add OSLO support as well.
> 
> I agree. Should I add it now or we can postpone it till
> 
> [US124002](https://rally1.rallydev.com/#/23525809118d/portfolioitemstreegrid?detail=%2Fuserstory%2F483493531896&fdp=true?fdp=true): [AQ] Translations

Whatever you think will be most convenient. If postponing, can you add it to the AC of that story?

**Comment by Vitalii-Misechko** [comment]
> Whatever you think will be most convenient. If postponing, can you add it to the AC of that story?

Sure. I've added OSLO to [AQ] Translations story

**Pull request merged**
