### PR TITLE
Update d2l-activity-alignments to 1.1.0

### PR DESCRIPTION
**Pull request by mpharoah-d2l**

### CODE REVIEW

**Comment by djw-test** [comment]
Should we really be removing all the carets?

**Comment by djwester** [comment]
Should we really be removing all the carets?

**Comment by mpharoah-d2l** [comment]
That's what happened when I ran `npm i`

**Comment by mpharoah-d2l** [comment]
I don't think the package-lock file should even have carats, should it? Since package-lock defines the specific versions being resolved.

**Comment by djwester** [comment]
> I don't think the package-lock file should even have carats, should it? Since package-lock defines the specific versions being resolved.

@svanherk do you know what it should do here?

**Comment by svanherk** [comment]
> @svanherk do you know what it should do here?

Yeah this definitely doesn't look right... I think this is another node/npm version issue.  Do you have `npm 6.8.0`?

**Comment by mpharoah-d2l** [comment]
I have `5.6.0`

**Comment by mpharoah-d2l** [comment]
Updated to latest version of npm. Now the diff is even bigger.
image

**Comment by svanherk** [comment]
That's not good... `node` version?  I have `9.9.0`, but I know it's worked for people on `10`

**Comment by mpharoah-d2l** [comment]
Deleted my `node_modules` folder and ran `npm i` again. Somehow that made it worse

**Comment by mpharoah-d2l** [comment]
Node version is `8.9.4`. My Linux VM has a slightly newer version of node, but a way older version of npm.

**Comment by svanherk** [comment]
> Deleted my node_modules folder and ran npm i again. Somehow that made it worse

Deleted `node_modules` and `package-lock.json`?

**Comment by mpharoah-d2l** [comment]
I think it might be fine now, though it moved everything around because reasons?

**Comment by mpharoah-d2l** [comment]
Nevermind, the CI didn't like that.

**Comment by mpharoah-d2l** [comment]
Changed my npm version to be exactly `6.8.0` and it looks better now I think. Earlier versions get rid of the `^`s and newer versions just ruin everthing

**Comment by svanherk** [comment]
> Changed my npm version to be exactly 6.8.0 and it looks better now I think. Earlier versions get rid of the ^s and newer versions just ruin everthing

That's not good news, but this does look as I'd expect (back to using `semver`)

**Pull request merged**
