### PR TITLE
bump activities

### PR DESCRIPTION
**Pull request by mdgbayly**

### CODE REVIEW

**Comment by mdgbayly** [comment]
Actually just realized might need to bump `siren-sdk` for your changes too. Also someone else has a PR in the works to bump BSI which is picking up some of our changes too. Will validate we have everything updated that we need.

**Comment by kieranderson** [comment]
Looks like that one is also bumping `siren-sdk`

**Comment by mdgbayly** [comment]
> Looks like that one is also bumping `siren-sdk`

Yep - just checking where they are - as they have all the changes we need. Will just close this one if that one gets through.

**Comment by dlockhart** [comment]
FYI this is going to conflict with #1873, which also bumps activities.

**Pull request closed without merging**
