### PR TITLE
Bumping activities version to 3.50.1

### PR DESCRIPTION
**Pull request by cbusmand2l**
FYI @dlockhart, @mdgbayly, @BhamelinD2L @wongvincent, @xiangqiyan

### CODE REVIEW

**Comment by AlexBedley** [comment]
Ok I give up. Here's what I got so far:

1. CI is failing because it cannot find a file in d2l-attachments
2. However, that file exists and the code looks like it should work
3. `npm run build` fails locally with the same error. The weird thing there is it's actually looking for the file relative to my current directory instead of the file that's importing it (`attachment-content.js`). So of course the file is not there. But the file is in the correct spot (`../helpers/attachment-utils.js`) relative to `attachment-content.js`
4. Just for fun I opened `../helpers/attachment-utils.js` to see what was in it. `defaultLink`, which is what `attachment-content.js` is specifically importing, is not in that file.

My guess is that d2l-attachments is using some weird babel thing which causes `defaultLink` to not be transpiled which makes `import` think it can't find the file (although the file is "there") since it's missing `defaultLink`. However I'm so deep into this I'm having a hard time keeping it straight, a second pair of eyes would be nice.

@mdgbayly you are the sole author of https://github.com/Brightspace/attachment. Would you mind taking a look and see if I forgot something obvious?

**Comment by mdgbayly** [comment]
@AlexBedley 

> @mdgbayly you are the sole author of https://github.com/Brightspace/attachment. Would you mind taking a look and see if I forgot something obvious?

That's pretty weird. Just taking a look...

defaultLink is in `attachment-utils` so not sure why it is causing the polymer build issues. We've just used it in a webpack based build prior to @ryantmer  adding it to BSI, so maybe some weird transpiler issue as you say.

https://github.com/Brightspace/attachment/blob/master/helpers/attachment-utils.js#L69

**Comment by dlockhart** [comment]
I have a PR up to fix the problem here:
https://github.com/Brightspace/attachment/pull/8

**Comment by mdgbayly** [comment]
> I have a PR up to fix the problem here:
> [Brightspace/attachment#8](https://github.com/Brightspace/attachment/pull/8)

@dlockhart Aha! Thanks!

**Pull request merged**
