### PR TITLE
Add d2l-table component

### PR DESCRIPTION
**Pull request by awikkerink**
I'm not sure about how to handle the old vui-table. The vui-table and grid stuff is still being used. I would like to eventually move these things to use the d2l-table component, but is deprecating the vui-table correct?

### CODE REVIEW

**Comment by dlockhart** [comment]
Absolutely, yes -- just remove whatever you want from here. Remember that when Daylight is OFF, it uses the other branch of BSI, not this one.

**Comment by dlockhart** [comment]
So I think you can completely remove all the VUI-table stuff, no need to even put it into "deprecated".

**Comment by awikkerink** [comment]
The grid.scss stuff is still needed in a few places. That will need to be migrated first

**Comment by awikkerink** [comment]
http://search.dev.d2l/source/xref/LSOne/lp/framework/web/D2L.Web/ui/DataGrid/

**Comment by dlockhart** [comment]
Ew :(, that makes me sad

**Comment by awikkerink** [comment]
Hey @dlockhart can you merge this?

**Comment by awikkerink** [comment]
Thanks!

**Comment by awikkerink** [comment]
Good to merge then?

**Comment by dlockhart** [comment]
Yep, looks good

**Pull request merged**
