### PR TITLE
DE38817 Cert: Update core to 1.43.4 to include template width fix

### PR DESCRIPTION
**Pull request by emil-furniss**
https://rally1.rallydev.com/#/29180338367d/detail/defect/387521069496

### CODE REVIEW

**Comment by AllanKerr** [comment]
> 1.43.3 @AllanKerr okay to be included?

I think it should be. The change I bumped it for for `1.43.3` is safe but I can't comment on `1.43.2` other changes that may have been made that didn't need a version bump yet.

**Comment by emil-furniss** [comment]
@mpharoah-d2l Is `1.43.2` safe to go in?

**Comment by mpharoah-d2l** [comment]
`1.43.2` fixes checkboxes to have them aligned to the top instead of the middle of milti-line text. It should be safe, but since it affects everything using the checkbox, it was held off until the next release to give time to find any unexpected changes. @dlockhart

**Comment by dlockhart** [comment]
Was OK with it getting in anytime after branching (i.e Monday), so should be fine.

**Comment by emil-furniss** [comment]
@dlockhart Sorry, just to clarify: So it's ok to go into 20.05 post-branching as a cert defect?

**Comment by dlockhart** [comment]
Oh sorry I missed that this was going into `20.05`... um... I think ideally it wouldn't go in. We waited until Monday to release it because we were worried about small regressions caused by spacing changes.

**Comment by emil-furniss** [comment]
Reverted to branching from `1.42.1`, including my changes on the new branch, and then referencing the branch directly here. No more inclusion of `1.42.2` or `1.42.3` required.

**Pull request merged**
