### PR TITLE
21.8 Engagment Dashboard Cert Bypass

### PR DESCRIPTION
**Pull request by NicholasHallman**
Updating the engagement dashboard for the august release. Includes translations, updates to settings form validation, and updated error states.

### CODE REVIEW

**Comment by bemailloux** [comment]
Target branch should be 20.21.8

**Review by bemailloux — APPROVED** [review]

**Comment by bemailloux** [comment]
Do we even still use Travis? I thought BSI was fully migrated to GH Actions.

**Comment by svanherk** [comment]
> Do we even still use Travis? I thought BSI was fully migrated to GH Actions.

The automated update PRs, merging, and syncing with the LMS all use GitHub Actions, but unfortunately the actual CI build is still using Travis.  It's definitely on the todo list to move it over to GH Actions, but hasn't happened yet.  The Travis builds are flakey though, and every day this rises a little more on my personal priority list lol

Seems like there was a flake here with Travis communication, you might need to push an empty commit?

**Comment by NicholasHallman** [comment]
> Seems like there was a flake here with Travis communication, you might need to push an empty commit?

Okay, will do thank you :)

**Pull request merged**
