### PR TITLE
Bump table version

### PR DESCRIPTION
**Pull request by awikkerink**

### CODE REVIEW

**Comment by awikkerink** [comment]
@dlockhart Is this acceptable, or are these other things still in progress?

This is to fix a conflict with d2l-typography

**Comment by awikkerink** [comment]
We can either update the d2l-typography version or freeze the d2l-image-action version

**Comment by dlockhart** [comment]
@awikkerink I've been away so not really sure about everything that's in progress right now. I noticed the typography change breaking a bunch of builds though... @njostonehouse @dbatiste ?

**Comment by awikkerink** [comment]
K. I'm freezing d2l-image-action version for now. Otherwise we'll need to update typography. I don't know if it is ready, so this seems safest

**Comment by njostonehouse** [comment]
@awikkerink @dlockhart @dbatiste just about ready to get the latest version of everything bumped up in the next release, including the new d2l-image-action, all of them depending on typography 5.

**Pull request merged**
