### PR TITLE
US104330: Update My Courses to remove the (obsolete) touch menu.

### PR DESCRIPTION
**Pull request by njostonehouse**

### CODE REVIEW

**Comment by njostonehouse** [comment]
@edwardg8 If you want your latest change to My Courses in this release, we can piggyback.

**Comment by edwardg8** [comment]
I also wanted to add the changes for syncing the overlay and the widget for pinned tab actions, so I'll release new my courses after that is done.

**Comment by edwardg8** [comment]
I'm not too sure if we want to get rid of the package-lock.json file though, if we do that, then all the patches we made to my courses will automatically be picked up by BSI, is that intended?

**Comment by njostonehouse** [comment]
@edwardg8 The package-log.json file isn't deleted, it just gets funny about its updates for some reason. Click in the diff to view the change.

**Comment by edwardg8** [comment]
Never mind, my bad, should have package-lock.json file change opened.

**Pull request merged**
