### PR TITLE
Update package-lock.json

### PR DESCRIPTION
**Pull request by djwester**

### CODE REVIEW

**Comment by djwester** [comment]
@svanherk do you know how I should resolve the build failure?  It looks like two different components want to use different versions of another component.

`d2l-activities` wants v3 of the `d2l-organizations' component but `d2l-enrollments` wants v4

Any ideas on how I resolve this?

**Comment by svanherk** [comment]
What repo are you trying to update?  I don't think you want _any_ additional changes, a lot of these are WCAG 2.1 updates that we don't want in ` 20.19.6`

**Comment by svanherk** [comment]
I would do your usual update process, but then unstage all changes except for the specific repo commit you want to update

**Comment by djwester** [comment]
closing to this open a new pr

**Pull request closed without merging**
