### PR TITLE
Jroach/d2l activities v2

### PR DESCRIPTION
**Pull request by jeroach**
Major version bump for `d2l-activities`
https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v2.0.0

This is for the renaming of `d2l-evaluation-hub` to `d2l-quick-eval`

### CODE REVIEW

**Comment by jeroach** [comment]
@svanherk this seems like a LOT of changes to `package-lock.json` - did I miss a cleanup step?

**Comment by svanherk** [comment]
Are you using `npm 6.8.0`?  I've seen this with older `npm` versions

**Comment by jeroach** [comment]
`6.1.0` :(

Will update and fix. Thanks.

**Comment by jeroach** [comment]
Well, that failed gloriously - going to start fresh and try again

**Comment by svanherk** [comment]
I've seen talk of issues with `6.9.0`, but not sure exactly what the symptoms look like for that

**Comment by jeroach** [comment]
There - just cherry picked the SHA for my change

**Comment by svanherk** [comment]
Were any filter changes needed as part of this?

**Comment by jeroach** [comment]
> Were any filter changes needed as part of this?

@CarolBusman Any comment on filters?

**Comment by jeroach** [comment]
I think we're good for the filter - looking at the fully generated `package-lock.json`
```
  "d2l-facet-filter-sort": {
      "version": "github:BrightspaceUI/facet-filter-sort#758224661ceb3d814862f79ebde62ba323e5b1e3",
      "from": "github:BrightspaceUI/facet-filter-sort#semver:^1",

"d2l-common": {
      "version": "github:BrightspaceHypermediaComponents/common#cf8f59e66ec48ee5d85607a64abcf5a4472dd237",
      "from": "github:BrightspaceHypermediaComponents/common#semver:^2",
      "dev": true,
      "requires": {
        "@polymer/polymer": "^3.0.0",
        "d2l-facet-filter-sort": "github:BrightspaceUI/facet-filter-sort#semver:^1",
        "d2l-polymer-siren-behaviors": "github:Brightspace/polymer-siren-behaviors#semver:^1"
      }
    },
```

Which matches the version and SHA here: https://github.com/BrightspaceUI/facet-filter-sort/releases/tag/v1.2.2

**Pull request merged**
