### PR TITLE
Fix context menu rendering issue when menu has hidden items

### PR DESCRIPTION
**Pull request by d2l-joelp**
US70736 - [UI] Hide Collapse this Widget
https://rally1.rallydev.com/#/51191528503d/detail/userstory/55021256329

Will not have any effect until PR#2586 in merged in the LP.

### CODE REVIEW

**Comment by ryantmer** [comment]
:+1: - same changes as the other PR, ja?

**Comment by d2l-joelp** [comment]
That's right, those changes were moved here instead.

**Comment by dlockhart** [comment]
These changes LGTM, but this was originally @dbatiste's thing so I'll defer to him.

**Comment by dbatiste** [comment]
Yep - Looks good.

**Comment by d2l-joelp** [comment]
Cool, just waiting for Ryan to finish up his testing then I'll merge. Thanks guys.

**Comment by ryantmer** [comment]
Testing done, all good :)

**Pull request merged**
