### PR TITLE
update rubric version

### PR DESCRIPTION
**Pull request by stevenao**

### CODE REVIEW

**Comment by mdulat** [comment]
Should bower-locker file also be updated?

**Comment by stevenao** [comment]
^0.78.0 - the caret sign should pickup new minor version. But, I made the change just to be safe... :)

**Comment by wongvincent** [comment]
because version is still 0.x, caret won't pick up new minor version, only the patches

**Comment by stevenao** [comment]
good point.. yeah, i got mixed up with the ~ sign.

**Pull request merged**
