### PR TITLE
use @brightspace-ui/core 1.79.4

### PR DESCRIPTION
**Pull request by AKobets**

### CODE REVIEW

**Comment by AKobets** [comment]
actually there is already another PR that inlcludes core bump https://github.com/Brightspace/brightspace-integration/pull/2492

**Comment by dlockhart** [comment]
I'd ignore #2492 for now as I think that's just @svanherk experimenting with automating all this :)

**Comment by svanherk** [comment]
Yeah that won't be merged for a little bit so I'd go ahead with this one, but it's coming along! 🤞

**Comment by AKobets** [comment]
BSI updated with ui core release 1.80.0

**Pull request closed without merging**
