### PR TITLE
US80190: Add a "d2l-heading-strong" class to modify headings to have …

### PR DESCRIPTION
**Pull request by njostonehouse**
…a stronger font weight.

### CODE REVIEW

**Comment by njostonehouse** [comment]
@dbatiste Does this seem reasonable? LinkHeadings used to have a bold and a not-bold version (awkwardly named "level2" and "level3") that got lost when those "levels" were changed to match heading levels for Daylight. This provides a way to apply a heavier weight to the headings without changing the rest of the style.

**Comment by dbatiste** [comment]
I suppose if that's what we need.  Looking at the 900 weight, it seems like a subtle difference.  Hopefully it's different enough that it doesn't look _mis-matchy._

Though... just as we remove light (one less network request), we add an extra bold.  :(

**Comment by njostonehouse** [comment]
Currently, nothing uses the 900 weight, it just seemed weird to let some heading values get bolded and not others. Would you prefer I remove it for now, and only add it in when there's a use case for it?

**Comment by dbatiste** [comment]
It's currently not included in the [font assets](https://github.com/Brightspace/font-generator/blob/master/src/config.json), so 900 isn't currently downloaded.  I'd rather not include it unless necessary.  Does the new typography design call for it?

**Comment by njostonehouse** [comment]
No, it doesn't. It was something I included for completion. I'm removing it, and some of the other unused code to be more succinct.

**Pull request merged**
