### PR TITLE
Bumping activities to 3.50.23

### PR DESCRIPTION
**Pull request by cbusmand2l**
fyi @dlockhart, @BraydonKains, @m6jones

### CODE REVIEW

**Comment by AlexBedley** [comment]
@dlockhart I think https://github.com/BrightspaceUI/core/pull/309 is causing some weirdness for this PR. Do I need to run something here to fix it?

**Comment by dlockhart** [comment]
Yep sorry I intended to release that and an update to BSI at almost the same time but got delayed. If you can wait 5 minutes I'll have a fix up.

**Comment by AlexBedley** [comment]
> Yep sorry I intended to release that and an update to BSI at almost the same time but got delayed. If you can wait 5 minutes I'll have a fix up.

Thanks for taking a look! No worries

**Comment by dlockhart** [comment]
Ok fixed -- I restarted your build.

**Pull request merged**
