### PR TITLE
US106001 Update my courses version

### PR DESCRIPTION
**Pull request by ciss1995**

### CODE REVIEW

**Comment by svanherk** [comment]
Shouln't we also see updates to the `organizations` and `enrollments` versions?  And `activities`?

**Comment by edwardg8** [comment]
This looks good, Organizations and enrollments are only in my-courses package.json I think.

**Comment by svanherk** [comment]
Agreed this looks good, we may want to wait until we have `activities` `3.1.0` to merge (need to update https://github.com/BrightspaceHypermediaComponents/activities/blob/master/components/d2l-activity-card/d2l-activity-card.js).  But merging this now shouldn't break anything, `d2l-activity-card` is only used in an FRA I believe.  Will leave that up to Cheick, he's working on this now I believe

**Comment by ciss1995** [comment]
I think that I will merge this and come back. We need to fix the tests in d2l-activity-card

**Pull request merged**
