### PR TITLE
Fix d2l.page.load event not being measured in IE11

### PR DESCRIPTION
**Pull request by awikkerink**
I just noticed telemetry wasn't being reported for IE11 with daylight on. This fixes it.

### CODE REVIEW

**Comment by dlockhart** [comment]
So just a timing issue based on the ordering of the event registration?

**Comment by awikkerink** [comment]
What was happening is that the HTMLImports shim was loading stuff after the `load` event

**Comment by joshassad** [comment]
Captured in Rally as [DE24297](https://rally1.rallydev.com/#/15545167705d/detail/defect/94899995820?fdp=true)

**Comment by awikkerink** [comment]
`d2l.page.display` was already being reported to Google Analytics, so this isn't required for 10.6.11

**Pull request merged**
