### PR TITLE
Certfix image-banner-overlay and my-courses

### PR DESCRIPTION
**Pull request by annabelsegalld2l**
These changes are for a certfix to allow auto-loading of images, after the behaviour was broken by changing the wrappers from simple-overlay to d2l-dialog-fullscreen.

### CODE REVIEW

**Review by svanherk — APPROVED** [review]
Looks good!

**Comment by svanherk** [comment]
Although, I wonder if it'll be mad these changes aren't listed: https://github.com/Brightspace/d2l-image-banner-overlay/pull/117/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by svanherk** [comment]
I don't _think_ so because the observer is already included and the iron-threshold can't be removed, so I'd expect the actual building to be fine.  But I did just kick off the auto update if you want to see what it comes up with an copy that

**Comment by annabelsegalld2l** [comment]
I added those dependencies to package.json to match the auto-update diff!

**Review by svanherk — APPROVED** [review]

**Pull request merged**
