### PR TITLE
Update htmleditor component to v1

### PR DESCRIPTION
**Pull request by grant-cleary**

### CODE REVIEW

**Comment by grant-cleary** [comment]
Ick, forgot to follow the steps for updating the package-lock. Will do that now.

**Comment by svanherk** [comment]
You'll also need to make sure every repo in BSI that's using the editor is also at your new version before you can bump it.  Which I think it's only `activities`?  But basically, your PR will need at minimum the bump in `package.json` that you have, and an `activities` and `html-editor` bump in `package-lock.json`

**Comment by grant-cleary** [comment]
> You'll also need to make sure every repo in BSI that's using the editor is also at your new version before you can bump it. Which I think it's only `activities`? But basically, your PR will need at minimum the bump in `package.json` that you have, and an `activities` and `html-editor` bump in `package-lock.json`

Yeah, I'm currently bumping the version in the activities editor, so I'm not going to bother updating this PR until that's done. :)

**Comment by grant-cleary** [comment]
The package-lock regeneration also updated a couple unrelated dependencies. Should I be overly concerned (like should I be manually removing those changes)?

**Review by svanherk — APPROVED** [review]

**Pull request merged**
