### PR TITLE
smaller bsi.js bundle

### PR DESCRIPTION
**Pull request by omsmith**
Minified file is smaller by about 7K

* don't use the pre-minified lie bundle
* remove unnecessary wrapper around page-loading
* bundle scripts with rollup, less boilerplate than the browerify bundle

### CODE REVIEW

**Comment by omsmith** [comment]
Haven't actually loaded it up in the LMS yet.

**Comment by awikkerink** [comment]
I did a quick check of the bundle, and it appears the promises are being excluded. Do we actually need to include lie?

**Comment by omsmith** [comment]
Yes it's needed for IE11. Looking into some other problems with the bundle as well

**Comment by awikkerink** [comment]
It looks like the `function Promise { ... }` is not being included because it is being exported, and the `import 'blah'` only handles global stuff, not exported stuff.

**Comment by omsmith** [comment]
Have it mostly fixed locally. Still saves ~5K. I'll push later once I figure out the final ponderings

**Pull request closed without merging**
