### PR TITLE
US88109 Ensure close button is always visible and hover is active on …

### PR DESCRIPTION
**Pull request by mdulat**
…entire area of button.

### CODE REVIEW

**Comment by dbatiste** [comment]
Hey Margaret, I'm unable to locate `US88109` to get more info.  Any chance you can provide some background on what was happening here, and why the z-index value is needed, and whether a smaller z-index value can be used?

**Comment by mdulat** [comment]
Sure. In the QuickLinks picker, the close (x) button is hidden behind other header elements. See screenshot attached. For types that don’t include the header elements, the close X is visible, but only clickable in the small area on the top and right of the element (the part that is visible in screenshot), and hover styling only appears in this small area as well.

It could probably be a smaller z-index value, but I’m not sure what value would be safe to use. Maybe 1 would suffice.

Margaret

**Comment by dbatiste** [comment]
Ok ya - I would suggest using `z-index: 1;` if possible.

**Comment by mdulat** [comment]
I guess I don't have permissions to merge. Can you do it please?

**Pull request merged**
