### PR TITLE
update rubric version to 0.133.0

### PR DESCRIPTION
**Pull request by stevenao**

### CODE REVIEW

**Comment by omsmith** [comment]
Hey @stevenao. I've got an updated rubrics (and another package) coming. Mind if I tack on to this?

**Comment by omsmith** [comment]
Hey @stevenao. How the heck do I update the version on rubrics? Haha

**Comment by stevenao** [comment]
https://github.com/Brightspace/d2l-rubric/blob/master/.travis.yml#L15

I usually make use of the `frauci-update-version` tool running during CI by manually trigger a Travis build on `master`. There is menu item in the `More Options` menu if you navigate to the Travis page.

**Comment by omsmith** [comment]
Okay cool. Thought that may have been it, but didn't want to screw with things too terribly. Thanks!

**Comment by mdgbayly** [comment]
I remember this coming up before now... it used to run automatically on PR merge, but I think someone disabled it - maybe to try and save some Saucelabs time... and this was the impact... seems backwards to me..

**Comment by omsmith** [comment]
Ran a build, but the bump (reasonably) failed because something else merged after. Started another one. Sorry for blocking you!

**Comment by wongvincent** [comment]
Oops! sorry

**Comment by stevenao** [comment]
I just updated the rubric version to 0.133.0 (from your build). You can do a pull and put your BrightspaceHypermediaComponents update there.

**Comment by omsmith** [comment]
Should be good now. Sorry for delaying you so long. I don't _get_ bower sometimes, so, not really sure where all those hashes are really coming from, but they appear to be working.

**Pull request merged**
