### PR TITLE
Bump HTML editor version to 1.7.11

### PR DESCRIPTION
**Pull request by grant-cleary**
Contains the following changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.7.10...v1.7.11

### CODE REVIEW

**Review by davewagler-d2l — APPROVED** [review]

**Comment by davewagler-d2l** [comment]
I see you changed in the lock file but what about the package.json?

**Comment by davewagler-d2l** [comment]
> I see you changed in the lock file but what about the package.json?

O I

**Comment by grant-cleary** [comment]
> I see you changed in the lock file but what about the package.json?

This isn't the first editor backport into 20.21.5, so `package.json` is already looking for ~1.7.

**Comment by grant-cleary** [comment]
GEE THANKS DAVE

**Pull request merged**
