### PR TITLE
Increase activities version

### PR DESCRIPTION
**Pull request by svanherk**

### CODE REVIEW

**Comment by svanherk** [comment]
FYI to anyone looking at this - the plan is to wait until after branching.  Let me know if something in here needed to be this release.

**Comment by jwong-d2l** [comment]
We're going to have to bump BSI in cert for our changes... is that okay?  What was the reason for waiting till after branching?

**Comment by svanherk** [comment]
Mostly so there was no confusion in the naming, if I name it 10.8.11 it probably wouldn't get in on time, so I was gonna name it 20.19.4 to make it clear what release it got in

**Comment by jwong-d2l** [comment]
so wait, we'll have to do two different releases of BSI to support our cert bypass work?

**Comment by dlockhart** [comment]
`10.8.11` needs to handle the possibility that the Polymer 3 feature flag might be disabled in production.

**Comment by svanherk** [comment]
Closing, we will do a fresh pull after branching

**Pull request closed without merging**
