### PR TITLE
using "polymer build" with polymer.json

### PR DESCRIPTION
**Pull request by dlockhart**
Removes the dependence on manually calling `polymer-build` and a separate HTML minification step.

I compared the un-minified assets before & after and things are almost identical. The only changes were a result of `polymer-cli` using a newer `polymer-build` under the covers that prefixes imports with `<html><body>`.

Comparing the minified assets before & after:

Import | Before Size | After Size | Before (gz -9) | After (gz -9)
------------ | ------------- | ------------ | ------------------ | ----------------
`bsi.html` | 42,248 | 41,226 | 11,812 | 11,552
`d2l-image-banner-overlay.html` | 23,653 | 25,498 | 6,871 | 7,042
`d2l-more-less.html` | 7,395 | 7,579 | 2,236 | 2,239
`d2l-my-courses.html` | 256,882 | 277,530 | 54,381 | 54,841
`d2l-rubric.html` | 7,715 | 7,746 | 2,038 | 2,029
`d2l-scroll-spy.html` | 3,117 | 3,117 | 1,134 | 1,122
`d2l-simple-overlay.html` | 129 | 129 | 144 | 144
`d2l-table.html` | 356 | 373 | 253 | 263
`shared_bundle_1.html` | 670,552 | 654,343 | 184,347 | 183,614
Total | 1,012,047 | 1,017,541 | 263,216 | 262,846

@svanherk, would you be able to try this branch on Windows to make sure everything still works?

### CODE REVIEW

**Comment by svanherk** [comment]
Doesn't seem to be any Windows issues, `npm i`, `npm run build` and `npm run serve` all working as expected 👍

**Comment by omsmith** [comment]
I'd be interested in the before/after on the `gzip -9` as well.

I can't fully comprehend where the size differences are coming from without looking. I assume the bundling strategy may have changed, but even then I wouldn't expect duplicates, so are more comments staying in now or something?

**Comment by omsmith** [comment]
Edited shady-css-parser to collapse the newlines on multiple selectors. doesn't really seem to matter, especially with the gzips.

| Name | Unzipped | Zipped |
| -------- | ------------ | ---------- |
| bsi.html | 41284 | 11553 |
| d2l-image-banner-overlay.html | 25445 | 7026 |
| d2l-more-less.html | 7579 | 2239 |
| d2l-my-courses.html | 277410 | 54777 |
| d2l-rubric.html | 7746 | 2029 |
| d2l-scroll-spy.html | 3117 | 1122 |
| d2l-simple-overlay.html | 129 | 144 |
| d2l-table.html | 370 | 258 |
| shared_bundle_1.html | 657568 | 183742 |
| Total | 1020648 | 262890 |

**Comment by dlockhart** [comment]
Yeah the newlines was what I noticed just casually looking at the differences as well. Also a bunch of extra semi-colons that got added in the JavaScript and the addition of `<html><body>` at the start and end of imports.

**Pull request merged**
