### PR TITLE
Bump outcomes-overall-achievement

### PR DESCRIPTION
**Pull request by rgoessl**

### CODE REVIEW

**Review by max-hao-d2l — APPROVED** [review]
Bumping minor versions is (semi) automated now
https://github.com/Brightspace/brightspace-integration/pull/2597/files
https://d2l.slack.com/archives/C0PHG3QB0/p1600710258003800

**Comment by svanherk** [comment]
Yeah https://github.com/Brightspace/brightspace-integration/pull/2597 that Max linked is merged now.  Hoping to add auto merge soon, but for now feel free to approve and merge the automated PR if you beat me to it!

**Comment by rgoessl** [comment]
> 
> 
> Bumping minor versions is (semi) automated now
> https://github.com/Brightspace/brightspace-integration/pull/2597/files
> https://d2l.slack.com/archives/C0PHG3QB0/p1600710258003800

Cool

**Comment by rgoessl** [comment]
Got auto bumped

**Pull request closed without merging**
